package model;

public enum TypeNotif {
    INIT, LINE_TOURNOI_SELECTED, LINE_MATCH_SELECTED, TOURNOI_UNSELECTED,MATCH_UNSELECTED, LINE_UPDATED,
    LINE_ADDED,CB1_SELECTED,CB2_SELECTED,ADD_MATCH,DELETE_MATCH
}
