@startuml SD_ADD_MATCH
autonumber
hide footbox
skinparam shadowing false
actor user as u
participant ":Tournoi" as v <<View>>
participant ":Match" as m
participant ":Controller" as c <<controller>>
participant ":ListeTournois" as lt <<ListeTournois>>
participant ":Tournois" as t <<Tournois>>

activate u
u -> v :setJoueur1(j1: Joueur)
activate v
deactivate v
u -> v :setJoueur2(j2: Joueur)
activate v
deactivate v
u -> v :setResultats(r : Resultats)
activate v
deactivate v
u -> v : addMatch()
deactivate u
activate v
create m
v -> m :new()
v -> m :Validate() :Error[]
activate m
m --> v :[]
deactivate m
v -> c :addMatch(Joueur j1, Joueur j2, Resultats r)
deactivate v
activate c
c -> lt : addMatch(Joueur j1, Joueur j2, Resultats r)
activate lt
lt -> t : addMatch(Joueur j1, Joueur j2, Resultats r)
activate t
t -> t : addMatch(Joueur j1, Joueur j2, Resultats r)
 t --> lt : boolean
 lt --> c : boolean
 c --> v : boolean
@enduml