@startuml diagramme de class
hide footbox
skinparam shadowing false
actor user as u 
usecase Tournois as t
usecase "Ajouter un match" as a
usecase "Modifier un match" as m
usecase "Supprimer un match" as s 
u -> t
t <|-- m : extends
t <|-- s : extends
t <|-- a : extends

@enduml