@startuml SD_DELETE_MATCH
autonumber
hide footbox
skinparam shadowing false
actor user as u
participant ":Delete" as v <<View>>
participant ":Controller" as c <<controller>>
participant ":ListeTournois" as lt <<ListeTournois>>
participant ":Tournois" as t <<Tournois>>
create v
activate u
activate c
c -> v :new(o : Match)
deactivate c
v -> v : fillViewDelete()
activate v
deactivate v
u -> v :deleteMatch(Match m)

activate v
v -> c :deleteMatch(int)
activate c
c -> lt :deleteMatch(int)
activate lt
lt -> t :deleteMatch(int)
activate t
t -> lt  : boolean
deactivate t
lt --> c : boolean
deactivate lt
c -> v :close()
deactivate c
deactivate v
deactivate u
@enduml