@startuml SSD_DELETE_MATCH
autonumber
hide footbox
skinparam shadowing false

actor user as u 
participant système as s
activate s
s -> u :affiche l'écran de confirmation
deactivate s
activate u
u -> s :confirme

activate s
s -> s :supprime le match
s -> s :mise à jour liste des matchs
s -> u :ferme l'écran de confirmation
s -> u :affiche la liste des matchs
deactivate s
deactivate u 
@enduml