@startuml SD_UPD_MATCH
hide footbox
skinparam shadowing false
actor user as u 
participant ":Tournoi" as v <<View>>
participant ":Controller" as c <<controller>>
participant ":ListeTournois" as lt <<ListeTournois>>
participant ":Tournois" as t <<Tournois>>


activate u
u -> v :setJoueur1(j1 : Joueur)
activate v
deactivate v
u -> v :setJoueur2(j2: Joueur)
activate v
deactivate v
u -> v :setResultats(r: resultats)
activate v
deactivate v
u -> v : updMatch(Joueur j1,Joueur j2,Resultats r)
deactivate u 
activate v
activate c
v -> c : updMatch(Joueur j1,Joueur j2,Resultats r)
activate lt
c -> lt : updMatch(Joueur j1,Joueur j2,Resultats r)
activate t
lt -> t :updMatch(Joueur j1,Joueur j2,Resultats r)
t -> t : set(Joueur j1,Joueur j2,Resultats r)
t --> lt : boolean
lt --> c : boolean
c --> v : boolean
deactivate v
deactivate lt
deactivate t
deactivate c
@enduml