@startuml CDL

skinparam shadowing false

package Model{
    class Tournoi{
        - String nom
    }
    class Match{
        -Joueur joueur1
        -Joueur joueur2
        -Resultats r
    }

    class Joueur{
        -String nom
    }
    class Resultats{
        -enum Resultats
    }
    class ListeTournois{
    }
}
package Controller{
    class Ctrl<<Controller>>{
        -selectedTournament : int
        -selectedMatch: int
        +findTournament(int)
        +addLineMatch()
        +lineSelection()
        +updLineMatch()
        +deleteLineMatch()
        +setJoueur1()
        +setJoueur2()
        +setResultat()
        +selectTournoi()
        +selectMatch()
        +selectUpdMatch(Joueur joueur1,Joueur joueur2, Resultats r)
        +selectAddMatch(Joueur joueur1,Joueur joueur2, Resultats r)
        +selectDeleteMatch(Match m)

    }
}
package View {
    class ConfirmationSuppressionMatch<<View>>{
        -Match deleteMatch
    }
     class GestionTournois<<View>>{
        -List<Tournois> listetournois
        -List<Match> listematchs
        -List<Joueur> listeJoueurs

    }
}
ListeTournois "1" o-r- "*" Tournoi : contient
Tournoi "1" o-r- "*" Match : contient
Tournoi "1" o-- "0*" Joueur : est inscrit
Match "1" *-- "2" Joueur :est composé
Match *-- Resultats
Controller ..> Model : use
View"1" <--"1" Controller
@enduml